### ISSUE TITLE
使用参考文档中的例子，把token换成自己的，一直报[Errno -2] Name or service not known错误

### ISSUE THREAD

**Issue by ety001** [url2io/issues#1]
如题。

**Comment by leilux** [comment]
Python-SDK还是url2io-app-samples中的pageless？

**Comment by ety001** [comment]
这个页面的例子：http://www.url2io.com/docs

http://api.url2io.com/article?token=xxx&url=http%3A%2F%2Furl2io.com%2Fdocs&fields=next,text

我替换了xxx为我自己的token，然后就报那个错误了。

我本地刚才开发的时候出了这个问题，所以我才用文档的例子测试了下。

现在我本地的问题找到了，是因为我把url编码了两次导致的。

**Comment by leilux** [comment]
哦哦，那现在问题应该解决了吧？
其实看出错后返回的 json 数据应该更清楚些，它会把出错的 url 也返回。如果编码了两次，那返回的 url 是不正常的。

**Comment by ety001** [comment]
恩，我本地的解决了，不过官网文档里的那个链接不知道为什么不行。

我本地刚才报错的那个信息里url的确还是编码的，最好能在文档里提示下，返回数据的url是没有编码的。

```
array(3) {
  'msg' =>
  string(36) "[Errno -2] Name or service not known"
  'url' =>
  string(92) "http://https%3A%2F%2Fraw.githubusercontent.com%2Fety001%2Furl2io%2Fmaster%2Ftests%2Ftestfile"
  'error' =>
  string(11) "UnknowError"
}
```

**Comment by ety001** [comment]
附加上出问题的链接：

http://api.url2io.com/article?token=nXMp2CFOT825EKHEEsZ_KQ&url=http%3A%2F%2Furl2io.com%2Fdocs&fields=next,text

你们测完了，帮我更新下token吧~ 顺带着@我下~

**Comment by ety001** [comment]
好吧。。。

我发现问题出在哪里了，你们的url2io.com没有做DNS解析啊。。。url里加上www.后就ok了。。。

看来是对于url不可访问的情况下的报错信息返回不是很完善。

**Comment by leilux** [comment]
哎～，我得把那个例子更新一下了。url2io.com 现在不是指向任何网站的
