### ISSUE TITLE
建议增加微信公众号文章支持

### ISSUE THREAD

**Issue by blueset** [url2io/issues#4]
RT。微信公众号的文章内容提取很简单，CSS Selector `#js_content` 即可。

**Comment by leilux** [comment]
现在用的算法是可以支持的，不过之前因为抓得太频繁被封过。因为目前还没有做IP代理，所以建议开发者先将网页抓取到后，再让URL2io去提取你抓取到的网页，把URL2io作为一个处理器的角色。不过以后会做IP代理。
对于图片的话，虽然支持惰性图片网址解析，对于微信得话开发者还需要稍微处理下（将`/img-src/0?wx_fmt=jpeg`改为`/img-src/640?wx_fmt=jpeg`）。URL2io的目标是尽可能不用规则去处理网页，所以就没有对微信做特别处理，不过对于微信图片这种情况的话可能算法是解决不了的，所以以后会考虑做特别的处理。
或者你说的是另外的情况？-_-

**Comment by blueset** [comment]
哦哦，那也就是说那些被墙的网址也可以通过反代的方式识别吗？
