### ISSUE TITLE
低密度文本识别优化

### ISSUE THREAD

**Issue by mahaoyang** [url2io/issues#7]
比如一些网站
文章标题没按规范写进\<title\>和\<h3\>里面，嵌入到了正文里
发布时间是‘今天’、‘10分钟前’，或嵌入正文里了
next_page 按钮也不是‘下一页’、‘next’，而是‘>’、页码、年份、‘more’、‘点击加载更多’、下拉一屏
（业内有公司实现了，也有商业API）

还有就是 从文章列表页提取文章链接(没看到公开实现的版本)

希望优化和添加相关功能
也欢迎技术交流

**Comment by leilux** [comment]
每个都提得非常好！

> 文章标题没按规范写进`<title>`和`<h3>`里面，嵌入到了正文里
> 发布时间是‘今天’、‘10分钟前’，或嵌入正文里了
> next_page 按钮也不是‘下一页’、‘next’，而是‘>’、页码、年份、‘more’、‘点击加载更多’、下拉一屏
> （业内有公司实现了，也有商业API）

这里提到的相关的示例网站能不能提供一下，便于我们开发可测试 ^_^
还有标题和内容不太符合啊…… 低密度文本相关的示例也可以提供一下

> 从文章列表页提取文章链接

这个是一直想做的功能，能够解决从哪里来的问题。

**Comment by mahaoyang** [comment]
http://bbs.t56.net/thread-5071270-1-1.html
时间提取为空

http://www.hebwst.gov.cn/index.do?id=372620&templet=content&cid=14
标题错误

**Comment by mahaoyang** [comment]
go版本和原版算法已经不一样了，不是很确定优劣，似乎各有所长，我再对比一阵子看看
